name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Build
        run: cd server ; go build 

      - name: Copy files to Azure server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_SERVER_HOST }}
          username: ${{ secrets.AZURE_SERVER_USERNAME }}
          password: ${{ secrets.AZURE_SERVER_PASSWORD }}
          source: "m"
          target: "/home/azureuser/VartaLabh/server"

      - name: SSH into Azure server and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_SERVER_HOST }}
          username: ${{ secrets.AZURE_SERVER_USERNAME }}
          password: ${{ secrets.AZURE_SERVER_PASSWORD }}
          script: |
            sudo systemctl restart goweb.service